[project]
name = "spotify-watcher"
version = "0.1.0"
description = "A tool to download your Spotify Playlists"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "questionary>=2.1.0",
    "rich>=13.9.4",
    "spotdl>=4.2.11",
]